calm_darkness_38642/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from drf_spectacular.views import SpectacularJSONAPIView, SpectacularSwaggerView
from .views import CustomLoginView
from home.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    CustomPasswordResetConfirmView,
    CustomPasswordChangeView,
    MobilePasswordResetView,
    VerifyOTPView,
)

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("modules/", include("modules.urls")),
    path("api/v1/", include("home.api.v1.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("coachees/", include("coachees.urls", namespace="coachees")),
    path("feedbacks/", include("feedbacks.urls", namespace="feedbacks")),
    # Override custom rest_auth apis, these must be above on "path("rest-auth/", include("rest_auth.urls"))"
    path("rest-auth/login/", CustomLoginView.as_view(), name="rest_login"),
    path(
        "rest-auth/password/change/",
        CustomPasswordChangeView.as_view(),
        name="rest_password_change",
    ),
    path(
        "rest-auth/password/reset/",
        PasswordResetView.as_view(),
        name="rest_password_reset",
    ),
    path(
        "rest-auth/password/reset/otp/",
        MobilePasswordResetView.as_view(),
        name="otp_password_reset",
    ),
    path("rest-auth/verify-otp/", VerifyOTPView.as_view(), name="verify_otp"),
    path(
        "new-password/<str:uidb64>/<str:token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("rest-auth/", include("rest_auth.urls")),
]


admin.site.site_header = "Sloan Leaders"
admin.site.site_title = "Sloan Leaders Admin Portal"
admin.site.index_title = "Sloan Leaders Admin"

# swagger
urlpatterns += [
    path("api-docs/schema/", SpectacularJSONAPIView.as_view(), name="schema"),
    path(
        "api-docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="api_docs"
    ),
]

urlpatterns += [re_path(r".*", TemplateView.as_view(template_name="index.html"))]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

notifications/models.py
from django.db import models
from django.core.exceptions import ValidationError
from users.models import User
from django.contrib.postgres.fields import JSONField


# Create your models here.
class Notification(models.Model):
    """
    Notification which is created from admin pannel
    """

    notification_name = models.CharField(max_length=50)
    notification_text = models.TextField(max_length=400)
    activate = models.CharField(max_length=20)
    receiver = models.CharField(max_length=10)
    date_time = models.DateTimeField(auto_now_add=True)


class NotificationHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification_name = models.CharField(max_length=200)
    notification_text = models.TextField(max_length=400)
    action_type = models.CharField(max_length=50, default="")
    data = JSONField(default=dict)
    is_read = models.BooleanField(default=False)
    date_time = models.DateTimeField(auto_now_add=True)

notifications/forms.py
from django import forms
from .models import Notification


class NotificationForm(forms.ModelForm):
    receiver_user = (("All", "All"), ("Coachee", "Coachee"), ("Coach", "Coach"))
    receiver = forms.ChoiceField(
        choices=receiver_user,
        widget=forms.Select(
            attrs={
                "class": "vTextField",
                "style": "margin-left: 17px; margin-right: 17px; width: 285px;",
                "id": "id_receiver",
                "maxlength": 110,
            }
        ),
    )
    CHOICE = (
        ("activate_one_time", "One Time"),
        ("every_day_at_8", "Every day at 8 AM EST"),
    )
    activate = forms.ChoiceField(choices=CHOICE)

    class Meta:
        model = Notification
        fields = [
            "notification_name",
            "notification_text",
            "activate",
            "receiver",
        ]
        widgets = {
            "notification_name": forms.TextInput(
                attrs={
                    "class": "vTextField",
                    "style": "margin-left: 17px; margin-right: 17px; width: 275px;",
                    "maxlength": 100,
                    "id": "id_notification_name",
                }
            ),
            "notification_text": forms.TextInput(
                attrs={
                    "class": "vTextField",
                    "style": "margin-left: 17px; margin-right: 17px; width: 275px;",
                    "maxlength": 100,
                    "id": "id_notification_text",
                }
            ),
        }

notifications/views.py
from django.shortcuts import render

# Create your views here.

notifications/templates/notification_admin/form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

<style>
    .custom-navbar {
        background-color: #79aec8;
        padding: 8px 15px;
        border-radius: 4px;
        margin-bottom: 0;
        color: white;
    }

    @media (min-width:767px) {
        .submit-button {
            text-align: right;
            background-color: white;
            border: none;
            width: 160px;
            position: relative;
            left: 305px;
            margin-top: -30px;
        }

        .input-btn {
            width: 125px;
            height: 30px !important;
            padding-top: 7.5px !important;
        }

    }

    @media (max-width:767px) {
        .text-checkbox {
            color: black;
            vertical-align: auto;
            margin-right: 20px;
            margin-top: 5px;
        }
    }

    @media (min-width:767px) {
        .submit-button {
            text-align: right;
            background-color: white;
            border: none;
        }
    }
</style>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            <h3 class="custom-navbar">Send Notification</h3>
        </div>
    </div>
</div>

<div id="content" class="colM">
    <div id="content-main">
        <form enctype="multipart/form-data" action="" method="post" id="language_form" novalidate="" name="add-form">
            {% csrf_token %}
            <div>
                <fieldset class="module aligned ">
                    <div class="form-row field-notification_name">
                        <div>
                            <label class="required" for="id_notification_name">Notification Name:</label>
                            {{form.notification_name}}
                        </div>
                    </div>

                    <div class="form-row field-notification_text">
                        <div>
                            <label class="required" for="id_notification_text">Notification Text: </label>
                            {{form.notification_text}}
                        </div>
                    </div>
                    <div class="form-row field-activate_one_time">
                        <div>
                            <label class="required" for="file">When it's activate:</label>
                            <ul id="id_activate" class="checkbox">
                                {% for value, label in form.activate.field.choices %}
                                <li>
                                    <label for="id_{{ value }}">
                                        <input type="checkbox" name="activate" value="{{ value }}"
                                            class="custom-checkbox"
                                            style="margin-left:17px; width:20px !important; height:20px !important"
                                            id="id_{{ value }}" onclick="handleCheckboxClick('id_{{ value }}')">
                                        {{ label }}
                                    </label>
                                </li>
                                {% endfor %}
                            </ul>

                        </div>
                    </div>
                    <div class="form-row field-receiver">
                        <div>
                            <label class="required" for="id_receiver">Select Receiver:</label>
                            {{form.receiver}}
                        </div>
                    </div>
                </fieldset>


                <div class="submit-row submit-button">

                    <!-- Submit Button -->

                    <input type="submit" class="input-btn" value="Submit" id="upload-btn"
                        style="background-color: #417690;" style="position: absolute; right: 0;">
                </div>

            </div>
        </form>
    </div>



    <br class="clear">
</div>
<!-- END Content -->

<div id="footer"></div>


<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            <h3 class="custom-navbar">Notification History</h3>
        </div>
    </div>
</div>

<script>
    function handleCheckboxClick(checkboxId) {
        var checkboxes = document.querySelectorAll('.checkbox input[type="checkbox"]');

        checkboxes.forEach(function (checkbox) {
            if (checkbox.id !== checkboxId) {
                checkbox.checked = false;
            }
        });
    }
</script>

notifications/templates/notification_admin/list.html
{% extends 'admin/change_list.html' %}
{% load i18n %}


{% block userlinks %}
<div id="user-tools">
    {% if user.is_active and user.is_staff %}
    <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> |
    {% endif %}
    <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
</div>
{% endblock %}


{% block object-tools %}
<!-- Remove add button on change_list.html -->
{% endblock %}



{% block content %}

{% include './form.html' %}

{{block.super}}
{% endblock %}