calm_darkness_38642/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from drf_spectacular.views import SpectacularJSONAPIView, SpectacularSwaggerView
from .views import CustomLoginView
from home.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    CustomPasswordResetConfirmView,
    CustomPasswordChangeView,
    MobilePasswordResetView,
    VerifyOTPView,
)

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("modules/", include("modules.urls")),
    path("api/v1/", include("home.api.v1.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("coachees/", include("coachees.urls", namespace="coachees")),
    path("feedbacks/", include("feedbacks.urls", namespace="feedbacks")),
    # Override custom rest_auth apis, these must be above on "path("rest-auth/", include("rest_auth.urls"))"
    path("rest-auth/login/", CustomLoginView.as_view(), name="rest_login"),
    path(
        "rest-auth/password/change/",
        CustomPasswordChangeView.as_view(),
        name="rest_password_change",
    ),
    path(
        "rest-auth/password/reset/",
        PasswordResetView.as_view(),
        name="rest_password_reset",
    ),
    path(
        "rest-auth/password/reset/otp/",
        MobilePasswordResetView.as_view(),
        name="otp_password_reset",
    ),
    path("rest-auth/verify-otp/", VerifyOTPView.as_view(), name="verify_otp"),
    path(
        "new-password/<str:uidb64>/<str:token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("rest-auth/", include("rest_auth.urls")),
]


admin.site.site_header = "Sloan Leaders"
admin.site.site_title = "Sloan Leaders Admin Portal"
admin.site.index_title = "Sloan Leaders Admin"

# swagger
urlpatterns += [
    path("api-docs/schema/", SpectacularJSONAPIView.as_view(), name="schema"),
    path(
        "api-docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="api_docs"
    ),
]

urlpatterns += [re_path(r".*", TemplateView.as_view(template_name="index.html"))]

coachees/urls.py
from django.urls import path
from coachees.views import AssignCoachView, session_report, final_report

app_name = "coachees"
urlpatterns = [
    path(
        "coachees/assign_coach/<int:pk>/",
        view=AssignCoachView.as_view(),
        name="assign_coach",
    ),
    path("<int:pk>/assign-coach/", view=AssignCoachView.as_view(), name="assign_coach"),
    path("session-report/<session_id>/", session_report, name="session-report"),
    path("final-report/<engagement_id>/", final_report, name="final-report"),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

coachees/views.py
from django.views import View
from coaches.models import Coach
from coachees.models import EngagementInfo, Coachee
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db import transaction
from django.contrib import messages
from .models import (
    Session,
    CoacheesReviews,
    CoachReviews,
    CoachFinalReportReview,
    CoacheesFinalReportReview,
)
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from calm_darkness_38642.schedular import notifications


class AssignCoachView(LoginRequiredMixin, View):
    template_name = "assign_coach.html"

    def get(self, request, pk):
        coachee = Coachee.objects.get(pk=pk)
        coaches = Coach.objects.all().order_by("first_name")

        # Get the already assigned coach and number of sessions for the coachee
        engagement_infos = coachee.engagement_infos.all()
        selected_coach_ids = [info.coach.id for info in engagement_infos]
        num_sessions = coachee.num_sessions
        choices = [("all", "All")] + [(str(coach), str(coach)) for coach in coaches]

        selected_filter = request.GET.get("coach_filter", "all")
        if selected_filter == "all":
            filtered_coaches = coaches
        else:
            filtered_coaches = coaches.filter(name=selected_filter)

        already_assigned_coaches = coachee.engagement_infos.values_list(
            "coach", flat=True
        )
        assigned_coaches = Coach.objects.filter(pk__in=already_assigned_coaches)

        return render(
            request,
            self.template_name,
            {
                "coachee": coachee,
                "coaches": filtered_coaches,
                "assigned_coaches": assigned_coaches,
                "coach_filter_choices": choices,
                "selected_coach_filter": selected_filter,
                "selected_coach_ids": selected_coach_ids,
                "num_sessions": num_sessions,
            },
        )

    @transaction.atomic
    def post(self, request, pk):
        coachee = Coachee.objects.get(pk=pk)
        selected_coach_ids = request.POST.getlist("coach_id")
        # get the list of selected coach IDs
        num_sessions = request.POST.get("num-sessions")

        # Check to not change anything after Start Engagement with any coach.
        if coachee.engagement_status == "Start Engagement":
            # Get the already assigned coach and number of sessions for the coachee
            coaches = Coach.objects.all()
            engagement_infos = coachee.engagement_infos.all()
            selected_coach_ids = [info.coach.id for info in engagement_infos]
            num_sessions = coachee.num_sessions
            choices = [("all", "All")] + [(str(coach), str(coach)) for coach in coaches]

            selected_filter = request.GET.get("coach_filter", "all")
            if selected_filter == "all":
                filtered_coaches = coaches
            else:
                filtered_coaches = coaches.filter(name=selected_filter)

            already_assigned_coaches = coachee.engagement_infos.values_list(
                "coach", flat=True
            )
            assigned_coaches = Coach.objects.filter(pk__in=already_assigned_coaches)
            context = {
                "coachee": coachee,
                "coaches": filtered_coaches,
                "assigned_coaches": assigned_coaches,
                "coach_filter_choices": choices,
                "selected_coach_filter": selected_filter,
                "selected_coach_ids": selected_coach_ids,
                "num_sessions": num_sessions,
                "error_message": "You couldn't change coaches or number of sessions after engagement started with any coach.",
            }
            return render(request, self.template_name, context)

        # Get the coaches that are already assigned to the coachee
        already_assigned_coaches = coachee.engagement_infos.values_list(
            "coach", flat=True
        )

        # Determine the coaches to be deselected (already assigned but not selected in the form)
        deselected_coaches = Coach.objects.filter(
            pk__in=already_assigned_coaches
        ).exclude(pk__in=selected_coach_ids)

        if deselected_coaches:
            # Delete the deselected coaches from the engagement_infos table
            coachee.engagement_infos.filter(coach__in=deselected_coaches).delete()

        if selected_coach_ids:
            selected_coaches = Coach.objects.filter(pk__in=selected_coach_ids)
            # get the list of selected coaches

            # Get the coaches that are not already assigned to the coachee
            unassigned_coaches = selected_coaches.exclude(
                pk__in=already_assigned_coaches
            )

            with transaction.atomic():
                for coach in unassigned_coaches:
                    engagement_info = EngagementInfo(coachee=coachee, coach=coach)
                    engagement_info.save()
                coachee.num_sessions = num_sessions
                coachee.coaching_status = "Assigned"
                coachee.save()
                # sending notification to the coachee
                notifications(
                    action_type="assign_coaches",
                    user_id=coachee.user_id,
                    notification_name="You have been assigned Coaches! Please take a look at their profiles and schedule Chemistry Calls.",
                    notification_text="",
                    fcm_data={"action_type": "assign_coaches"},
                )
            messages.success(request, "Coaches successfully assigned to coachee.")
            changelist_url = reverse("admin:coachees_coachee_changelist")
            return redirect(changelist_url)
        else:
            context = {
                "coachee": coachee,
                "assigned_coaches": Coach.objects.filter(pk__in=selected_coach_ids),
                "coaches": Coach.objects.all(),
                "num_sessions": num_sessions,
                "error_message": "Please select one or more coaches and enter the number of sessions.",
            }
            return render(request, self.template_name, context)


def session_report(request, session_id):
    try:
        session_obj = Session.objects.get(id=session_id)
        coachee_object = Coachee.objects.get(id=session_obj.engagement_info.coachee_id)
        coach_obj = Coach.objects.get(id=session_obj.engagement_info.coach_id)
        coach_review = CoachReviews.objects.filter(session_id=session_obj.id)
        coachee_review = CoacheesReviews.objects.filter(session_id=session_obj.id)
        return render(
            request,
            "admin/coachees/coaching_report.html",
            {
                "coachee": coachee_object,
                "session": session_obj,
                "coach": coach_obj,
                "coach_review": coach_review.first(),
                "coachee_review": coachee_review.first(),
            },
        )
    except:
        return HttpResponseRedirect("/admin/coachees/coachee/")


def final_report(request, engagement_id):
    try:
        engagement_info = EngagementInfo.objects.get(id=engagement_id)
        coachee_object = Coachee.objects.get(id=engagement_info.coachee_id)
        coach_obj = Coach.objects.get(id=engagement_info.coach_id)
        coach_review = CoachFinalReportReview.objects.filter(
            engagement_info_id=engagement_id
        )
        coachee_review = CoacheesFinalReportReview.objects.filter(
            engagement_info_id=engagement_id
        )
        return render(
            request,
            "admin/coachees/final_report.html",
            {
                "coach": coach_obj,
                "coachee": coachee_object,
                "engagement": engagement_info,
                "coach_review": coach_review.first() if coach_review.exists() else None,
                "coachee_review": coachee_review.first()
                if coachee_review.exists()
                else None,
            },
        )
    except:
        return HttpResponseRedirect("/admin/coachees/coachee/")

coachees/templates/assign_coach.html
{% extends "admin/base.html" %}
{% load static %}
{% load admin_urls %}
{% load i18n %}
{% block title %}
{{ title }} Assign Coach To a Coachee | {% trans 'Sloan Leaders' %}
{% endblock %}
{% block branding %}
    <div class="header">
        <div id="branding">
            <h1 id="site-name"><a href="/admin/">{% trans 'Sloan Leaders' %}</a></h1>
        </div>
        <div id="user-tools">
            {% trans 'WELCOME,' %}
            <strong>{{ user.username }}.</strong>
            <a href="/">{% trans 'VIEW SITE' %}</a> /
            <a href="/admin/password_change/">{% trans 'CHANGE PASSWORD' %}</a> /
            <a href="/admin/logout/">{% trans 'LOG OUT' %}</a>
        </div>
    </div>
{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    › <a href="{% url 'admin:coachees_coachee_changelist' %}">{% trans 'Coachees' %}</a>
    › <span class="breadcrumb-active">{% trans 'Assign Coach' %}</span>
</div>
{% endblock %}
{% block content %}
{% if error_message %}
<ul class="messagelist">
    <li class="error">{{ error_message }}</li>
</ul>
{% endif %}
<div class="col-md-6 ">
    <h1 class="heading1" >Assign Coach</h1>
    <form action="{% url 'coachees:assign_coach' pk=coachee.id %}" method="post">

      {% csrf_token %}
      <div class="clientname">
        <label for="client-name" class="client_name" >Client Name:</label>
        <input type="text" name="client-name" class="client-name" id="client-name" value="{{ coachee.client }}" readonly>
      </div>
      <link rel="stylesheet" type="text/css" href="{% static 'css/admin_style.css' %}">
      <div class="select_coach" >
        <label for="select-coach" class="select-coach">Select Coaches:</label>
        <select name="coach_id" class="form-control select-dropdown" id="select-coach" multiple multiselect-search="true" multiselect-select-all="true">
          {% for coach in assigned_coaches %}
            <option value="{{ coach.id }}" {% if coach.id in selected_coach_ids %}selected{% endif %}>{{ coach }}</option>
          {% endfor %}
          {% for coach in coaches %}
            {% if coach not in assigned_coaches %}
              <option value="{{ coach.id }}">{{ coach }}</option>
            {% endif %}
          {% endfor %}
        </select>          
      </div>
      <script src="{% static 'js/script.js' %}"></script>
        <div class="numsession">
          <label for="num-sessions" class="num-sessions">Number of Sessions:</label>
          <input type="number" name="num-sessions" class="client-name" id="num-sessions" value="{{ num_sessions }}">
          <span id="num-sessions-error" style="color: red;"></span>
        </div>
      <button type="submit" class="btn-assign-coach" >Assign Coaches</button>
    </form>
  </div>


<script>
  document.querySelector('form').addEventListener('submit', function (event) {
    var numSessionsInput = document.getElementById('num-sessions');
    var numSessionsValue = parseInt(numSessionsInput.value);

    // Check if the value is 0 or negative
    if (numSessionsValue <= 0) {
      event.preventDefault(); // Prevent form submission
      document.getElementById('num-sessions-error').textContent = 'Number of Sessions must be greater than 0.';
    } else {
      // Clear the error message if the input is valid
      document.getElementById('num-sessions-error').textContent = '';
    }
  });
</script>

{% endblock %}

{% block extrahead %}
{{ block.super }}
{% endblock %}

coachees/templates/coachees_email.html
<!DOCTYPE html>
<html>

<head>
  <title>Sloan Leaders</title>
</head>

<body>
  <p>Hello,</p>
  <p>Welcome to Sloan Leaders!</p>
  <p>Your employer {{ client_name }} has added you to the Sloan Leaders system for Executive Coaching. Your journey
    begins today!</p>
  <p>Click <a href="{{login_url}}">here</a> to login to our Web Portal or download our app from the Apple App Store or
    Google Play Store.</p>
  <p>Your credentials:</p>
  <ul>
    <li>Email: {{ username }}</li>
    <li>Password: {{ password }}</li>
  </ul>
  <p>Thank you,</p>
  <p>- Sloan Leaders</p>
</body>

</html>

coachees/templates/session_email.html
<!DOCTYPE html>
<html>

<head>
  <title>Sloan Leaders</title>
</head>

<body>
  <p>Hello,</p>
  <p>You're receiving this e-mail because you have scheduled a {{call_type_name}} with {{name}} on {{date}}
    {{start_time}} - {{end_time}} EST.</p>

  <p>Thank you,</p>
  <p>- Sloan Leaders</p>
</body>

</html>